name: visimark
on: [push, pull_request]
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: michal-niedzwiedzki/visimark@v0.1.3
        with:
          files: "gpus.md"
